In [1]:
import pandera.pandas as pa
import pandas as pd
from pandera import Column, DataFrameSchema, Check

In [2]:
df = pd.read_csv('C:/Users/aksha/Loan_default_dataset/data/loan_dataset_20000.csv')

In [3]:
df.head(2)

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,loan_term,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies,loan_paid_back
0,59,Male,Married,Master's,24240.19,2020.02,Employed,0.074,743,17173.72,...,36,581.88,B5,7,40833.47,24302.07,1,0,1,1
1,72,Female,Married,Bachelor's,20172.98,1681.08,Employed,0.219,531,22663.89,...,60,573.17,F1,5,27968.01,10803.01,1,0,3,1

In [4]:
df['loan_id'] = 10000000 + df.index

In [5]:
df.head()

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies,loan_paid_back,loan_id
0,59,Male,Married,Master's,24240.19,2020.02,Employed,0.074,743,17173.72,...,581.88,B5,7,40833.47,24302.07,1,0,1,1,10000000
1,72,Female,Married,Bachelor's,20172.98,1681.08,Employed,0.219,531,22663.89,...,573.17,F1,5,27968.01,10803.01,1,0,3,1,10000001
2,49,Female,Single,High School,26181.80,2181.82,Employed,0.234,779,3631.36,...,76.32,B4,2,15502.25,4505.44,0,0,0,1,10000002
3,35,Female,Single,High School,11873.84,989.49,Employed,0.264,809,14939.23,...,468.07,A5,7,18157.79,5525.63,4,0,5,1,10000003
4,63,Other,Single,Other,25326.44,2110.54,Employed,0.260,663,16551.71,...,395.50,D5,1,17467.56,3593.91,2,0,2,1,10000004

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   20000 non-null  int64
 1   gender                20000 non-null  object
 2   marital_status        20000 non-null  object
 3   education_level       20000 non-null  object
 4   annual_income         20000 non-null  float64
 5   monthly_income        20000 non-null  float64
 6   employment_status     20000 non-null  object
 7   debt_to_income_ratio  20000 non-null  float64
 8   credit_score          20000 non-null  int64
 9   loan_amount           20000 non-null  float64
 10  loan_purpose          20000 non-null  object
 11  interest_rate         20000 non-null  float64
 12  loan_term             20000 non-null  int64
 13  installment           20000 non-null  float64
 14  grade_subgrade        20000 non-null  object
 15  num_of_open_accounts  20000 non-null  int64
 16  total_credit_limit    20000 non-null  float64
 17  current_balance       20000 non-null  float64
 18  delinquency_history   20000 non-null  int64
 19  public_records        20000 non-null  int64
 20  num_of_delinquencies  20000 non-null  int64
 21  loan_paid_back        20000 non-null  int64
 22  loan_id               20000 non-null  int64
dtypes: float64(8), int64(9), object(6)
memory usage: 3.5+ MB

In [7]:
df.columns

Index(['age', 'gender', 'marital_status', 'education_level', 'annual_income',
       'monthly_income', 'employment_status', 'debt_to_income_ratio',
       'credit_score', 'loan_amount', 'loan_purpose', 'interest_rate',
       'loan_term', 'installment', 'grade_subgrade', 'num_of_open_accounts',
       'total_credit_limit', 'current_balance', 'delinquency_history',
       'public_records', 'num_of_delinquencies', 'loan_paid_back', 'loan_id'],
      dtype='object')

In [8]:
df = df[['loan_id', 'age', 'gender', 'marital_status', 'education_level', 'annual_income',
       'monthly_income', 'employment_status', 'debt_to_income_ratio',
       'credit_score', 'loan_amount', 'loan_purpose', 'interest_rate',
       'loan_term', 'installment', 'grade_subgrade', 'num_of_open_accounts',
       'total_credit_limit', 'current_balance', 'delinquency_history',
       'public_records', 'num_of_delinquencies', 'loan_paid_back']]

In [9]:
df['loan_default'] = 1 - df['loan_paid_back']

In [10]:
df.loan_default.value_counts()

loan_default
0    15998
1     4002
Name: count, dtype: int64

In [11]:
df['gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [12]:
high_colinearity = ['annual_income', 'delinquency_history', 'grade_subgrade', 'loan_paid_back']

new_df = df.drop(columns=high_colinearity)

In [13]:
df['employment_status'].value_counts()

employment_status
Employed         13007
Self-employed     2923
Unemployed        2113
Retired           1176
Student            781
Name: count, dtype: int64

In [14]:
new_df.head()

,loan_id,age,gender,marital_status,education_level,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,loan_purpose,interest_rate,loan_term,installment,num_of_open_accounts,total_credit_limit,current_balance,public_records,num_of_delinquencies,loan_default
0,10000000,59,Male,Married,Master's,2020.02,Employed,0.074,743,17173.72,Car,13.39,36,581.88,7,40833.47,24302.07,0,1,0
1,10000001,72,Female,Married,Bachelor's,1681.08,Employed,0.219,531,22663.89,Debt consolidation,17.81,60,573.17,5,27968.01,10803.01,0,3,0
2,10000002,49,Female,Single,High School,2181.82,Employed,0.234,779,3631.36,Business,9.53,60,76.32,2,15502.25,4505.44,0,0,0
3,10000003,35,Female,Single,High School,989.49,Employed,0.264,809,14939.23,Other,7.99,36,468.07,7,18157.79,5525.63,0,5,0
4,10000004,63,Other,Single,Other,2110.54,Employed,0.260,663,16551.71,Car,15.20,60,395.50,1,17467.56,3593.91,0,2,0

In [15]:
new_df[new_df['num_of_open_accounts'] >= 15]

,loan_id,age,gender,marital_status,education_level,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,loan_purpose,interest_rate,loan_term,installment,num_of_open_accounts,total_credit_limit,current_balance,public_records,num_of_delinquencies,loan_default
565,10000565,53,Male,Divorced,PhD,1800.44,Employed,0.055,760,11635.76,Other,10.44,60,249.75,15,44701.73,16602.42,0,2,0
6923,10006923,31,Female,Single,Bachelor's,4493.81,Retired,0.169,666,12750.74,Debt consolidation,11.58,60,280.93,15,93434.66,30971.47,0,2,0
19480,10019480,21,Other,Single,PhD,7848.38,Employed,0.260,705,13854.42,Debt consolidation,11.03,60,301.44,15,69377.78,56624.78,0,2,0

In [16]:
cat_cols = new_df.select_dtypes(include='object').columns.tolist()
for col in cat_cols:
    new_df[col] = new_df[col].str.capitalize()

In [17]:
schema = DataFrameSchema({
    'age' : Column(int, checks=Check.in_range(18, 100), nullable=False),
    'gender' : Column(str, checks=Check.isin(['Male', 'Female', 'Other']), nullable=False),
    'marital_status': Column(str, checks=Check.isin(['Single', 'Married', 'Widowed', 'Divorced']), nullable=False),
    'education_level': Column(str, checks=Check.isin(["Bachelor's", 'High school', "Master's", 'Other', 'Phd']), nullable=False),
    'monthly_income' : Column(float, checks=Check.ge(0.0), nullable=False),
    'employment_status': Column(str, checks=Check.isin(["Employed", 'Self-employed', "Unemployed", 'Retired', 'Student']), nullable=False),
    'debt_to_income_ratio': Column(float, checks=Check.in_range(0.0, 1.0), nullable=False),
    'loan_amount': Column(float, checks=Check.ge(0.0), nullable=False),  
    'credit_score': Column(int, checks=Check.in_range(300, 900), nullable=False),
    'loan_purpose': Column(str, checks=Check.isin(['Debt consolidation', 'Other', 'Car',
                                                   'Home', 'Education', 'Business', 'Medical', 'Vacation']), nullable=False),
    'interest_rate': Column(float, checks=Check.in_range(0.0, 25.0), nullable=False),
    'loan_term': Column(int, checks= Check.in_range(12, 60), nullable=False),
    'installment': Column(float, checks=Check.ge(0.0), nullable=False),
    'num_of_open_accounts': Column(int, nullable=False),
    'total_credit_limit': Column(float, checks=Check.ge(0.0), nullable=False),
    'current_balance': Column(float, checks=Check.ge(0.0), nullable=False),
    'public_records': Column(int, nullable=False), 
    'num_of_delinquencies': Column(int, nullable=False),
    'loan_default': Column(int, checks=Check.isin([0, 1]), nullable=False)
})

C:\Users\aksha\anaconda3\envs\ml_env\Lib\site-packages\pandera\_pandas_deprecated.py:143: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

In [18]:
valid_df = schema.validate(new_df)

In [19]:
valid_df.head()

,loan_id,age,gender,marital_status,education_level,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,loan_purpose,interest_rate,loan_term,installment,num_of_open_accounts,total_credit_limit,current_balance,public_records,num_of_delinquencies,loan_default
0,10000000,59,Male,Married,Master's,2020.02,Employed,0.074,743,17173.72,Car,13.39,36,581.88,7,40833.47,24302.07,0,1,0
1,10000001,72,Female,Married,Bachelor's,1681.08,Employed,0.219,531,22663.89,Debt consolidation,17.81,60,573.17,5,27968.01,10803.01,0,3,0
2,10000002,49,Female,Single,High school,2181.82,Employed,0.234,779,3631.36,Business,9.53,60,76.32,2,15502.25,4505.44,0,0,0
3,10000003,35,Female,Single,High school,989.49,Employed,0.264,809,14939.23,Other,7.99,36,468.07,7,18157.79,5525.63,0,5,0
4,10000004,63,Other,Single,Other,2110.54,Employed,0.260,663,16551.71,Car,15.20,60,395.50,1,17467.56,3593.91,0,2,0

In [21]:
valid_df['marital_status'].value_counts()

marital_status
Single      9031
Married     8974
Divorced    1428
Widowed      567
Name: count, dtype: int64

In [24]:
valid_df['loan_purpose'].unique()

array(['Car', 'Debt consolidation', 'Business', 'Other', 'Home',
       'Medical', 'Education', 'Vacation'], dtype=object)